### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by sehyun-hwang** [scapix-com/scapix-bin#1]
I am looking to do an Open CV project for Apple devices with your project,
and I got into trouble due to my M1 powered mac.

In the native arm64 setting, the following log shows up whatever examples I try on your github account:

```
CMake Error at /opt/homebrew/Cellar/cmake/3.19.3/share/cmake/Modules/FetchContent.cmake:977 (message):
  CMake step for scapix_bin-2.0.8 failed: 1
```

Can you release an arm64 version of scapix for Mac OS?
Thank you.

**Comment by Boris-Rasin** [comment]
Thank you for reporting this issue.
I have built arm64 version for macOS.
Unfortunately I don't have arm64 Mac to test it (I cross compiled it on x86_64 Mac), so you will have to test it for me.
Please use the latest version of [cmodule](https://github.com/scapix-com/cmodule) in your CMake file:

```cmake
FetchContent_Declare(
  cmodule
  URL "https://github.com/scapix-com/cmodule/archive/v1.0.26.tar.gz"
  URL_HASH SHA256=d60f71844eb072ce1f45737175ec505bd88b4d75a65b479381aa5e077b902f18
)
```

Please report the result, whatever it is.
Thanks again.

**Comment by sehyun-hwang** [comment]
There is some uncertanty, because not all open source projects needed for this to work are compatable with M1 Macs, but the Python bridge example does not seem to work. Cmake exits correctly on Intel linux, but on my Mac, following error occurs:

```
cmake --build build/default_python
[ 10%] Built target scapix
[ 15%] Running Scapix Bridge for source/chat/folder/element.h
/bin/sh: /Users/hwangsehyun/.cmodule/scapix_bin/2.0.8/Darwin-x86_64/scapix: No such file or directory
make[2]: *** [../../generated/bridge/java/element.cpp] Error 127
make[1]: *** [CMakeFiles/chatlib.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by Boris-Rasin** [comment]
It seems CMake is looking for 'Darwin-x86_64/scapix' which means CMake thinks it's running on x86_64 Mac, not arm64 Mac. It is supposed to look for 'Darwin-arm64/scapix' instead.

Can you please try with CMAKE_APPLE_SILICON_PROCESSOR=arm64 variable:

```cmake
cmake -B build/default_python -DSCAPIX_BRIDGE=python -DCMAKE_APPLE_SILICON_PROCESSOR=arm64
cmake --build build/default_python
```

**Comment by sehyun-hwang** [comment]
That was resolved after upgrading cmake, and now Python binding works!
I felt bumping cmake version to latest and including setup.py on your python example could make your project better. I am willing to summit a pull request if you do not mind.
Thank you very much!

**Comment by Boris-Rasin** [comment]
Thanks!
Pull request would be great.
Did you have to specify "-DCMAKE_APPLE_SILICON_PROCESSOR=arm64"?
Or just upgrading CMake to latest version solved the issue?

**Comment by sehyun-hwang** [comment]
The upgrade was enough. I will look to submit a pull request to example1 repository soon. Thank you.
